name: coveralls

on:
  push:
    branches: [master, development]
  pull_request:
    branches: [master, development]

jobs:
  coveralls:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install packages
        run: pip install tox coveralls

      - name: Run coverage
        run: tox -e py38

      # see: https://coveralls-python.readthedocs.io/en/latest/usage/configuration.html#github-actions-support
      - name: Upload coverage data to coveralls.io
        run: coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
